name: Yarn Build and Lint

on: push

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run lint
        run: yarn lint
